{
    "language": "node_js",
    "node_js": "7.10",
    "script": [
        "npm run test"
    ],
    "group": "stable",
    "dist": "precise",
    "os": "linux",
    "services": "mongodb"
    "after_script": "./node_modules/coveralls/bin/coveralls.js ./coverage/lcov.info"
}
